### ISSUE TITLE
Using WPT profiles with CDT throttling provides misleading results

### ISSUE THREAD

**Issue by patrickhulce** [justinribeiro/lighthouse-action#4]
Hey @justinribeiro awesome action, love the involvement here!! 😍 

A quick note though on using WPT profiles with CDT throttling as-is. WPT profiles are specified with latency at the packet level, i.e. RTT at the transport layer, while CDT expects throttling settings at the request level, i.e. RTT at the application layer. 

The latency needed to be applied at the request level to see similar performance numbers is often several multiples of the latency at the packet level to account for the latency of DNS lookups, SSL handshakes, TCP handshakes, slow start, etc. You'll find these [adjustment factors in the LH repo](https://github.com/GoogleChrome/lighthouse/blob/6e5fc878f8cc69e00620b20092bfad1da6c1e4e2/lighthouse-core/config/constants.js#L8-L15) as well.

Love the ease with which folks can opt for different WPT profiles and the clever solution you've got to apply them! Awesome job here and carry on :D

(I think this might also apply to your jest example repo)

**Comment by justinribeiro** [comment]
Hi @patrickhulce! Yeahhhh......that was an oversight on my part (same with the jest example repo as well). I happened across this very problem when eyeballing numbers this morning; numbers are bit skewed. :-)

I'm going to patch this up with said adjust factors (cheers for the direct link).
