### ISSUE TITLE
Local directory over URL

### ISSUE THREAD

**Issue by Berkmann18** [justinribeiro/lighthouse-action#7]
This looks great and indeed provides the comment report which no other actions do.
I'm curious as to why it works on URLs while being targetted towards PRs when normally, you'll test `dist/`/`public/`/`static/` directories affected by the PR before it hits a production URL?
Wouldn't this action be better suited for `master` `push` events with the URL or does your build process allow such a thing?
I'm aware that's possible with services like Netlify but not with say GH Pages.

**Comment by justinribeiro** [comment]
> I'm curious as to why it works on URLs while being targetted towards PRs when normally, you'll test dist//public//static/ directories affected by the PR before it hits a production URL?

Because the goal is to roll your PR to a target staging environment to give you as close to a 1:1 perf measure as possible. An example of that workflow is here https://github.com/justinribeiro/blog-pwa/blob/master/.github/workflows/main.yml
